### PR TITLE
Add optional + nullify

### PR DESCRIPTION
**Pull request by laviallb**
Change-Id: Iab7257237cba6826daea108c9a07e475c7160a5a

### CODE REVIEW

**Comment by felginep** [comment]
I understand what you want to do, but i'm not sure with the naming. 
IMO the method `nullify` means you want to nullify the object, or it's the opposite, you want to keep the object if it verifies a condition. 

I would rather imagine a method like this (btw i do not see the point of using static method here, nor `flatMap` instead of `map`):

```
extension Optional {
    func verifying(_ test: (Wrapped) -> Bool) -> Optional<Wrapped> {
        return (map(test) ?? false) ? self : nil
    }
}
```

Considering the two alternatives, I think the second one is more legible:
```
guard let value = .nullify(input, failing: { !$0.isEmpty }) { ... }

guard let value = input.verifying({ !$0.isEmpty }) { ... }
```

**Comment by laviallb** [comment]
When using a static method over Optional, the object to be verified is a parameter, allowing to provide a non-optional implicitly casted as Optional.
This let the method work for both Optional and non-Optional objects.

**Comment by felginep** [comment]
Indeed, but what's the advantage of using `.nullify` on a non optional object ?

**Comment by laviallb** [comment]
to nullify it if it doesn't pass the test.

it simplifies both:

let validatedValue = optionalValue.flatMap { $0.passTheTest ? $0 : nil } (or (optionalValue?.passTheTest ?? false) ? optionalValue ? nil

and

let validatedValue = value.passTheTest ? value : nil

**Comment by felginep** [comment]
Ah ok. I thought the use case was for `guard` and `if let` (which would be nice!)

If you want to stick with the static function anyway, you could rename it `verifyOrNil` maybe, to better understand its purpose.

And I'm not convinced with the static approach, maybe a free function will work better to avoid forgetting about the dot when you want to type `.verifyOrNil`. Because you have to remember that the function is on an optional value, which is not convenient.

As a side note, did you consider throwing instead of nillify when validating multiple inputs ? (maybe there is inspiration here https://github.com/pointfreeco/swift-validated)

**Comment by laviallb** [comment]
Well, I guess in most cases it will be used inside `if let` and `guard let`, but its not required.

Indeed going with free function simplify the code.

**Comment by felginep** [comment]
Can you add the optional extension as well ? If the major use case is `if let` / `guard` it will be helpful

**Review by felginep — DISMISSED** [review]

**Review by felginep — APPROVED** [review]

**Pull request merged**
